# -*- coding: utf-8 -*-
"""MBTI test+AI voice chat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWqanBVmfG_JkBCDWKtHlXxnKtM9gev1
"""

# 安装 Gradio（Install Gradio）
!pip install gradio --upgrade

import gradio as gr
import random

# ───────────── 1. 题目和选项（Questions and Options） ─────────────
questions = [
    {"text": "I feel energised when I am with others. / 和他人在一起时，我会感到充满能量。"},
    {"text": "I prefer to think quietly rather than participate in group activities. / 我更喜欢安静思考，而不是参加群体活动。"},
    {"text": "I often initiate conversations in social situations. / 我经常在社交场合主动开始对话。"},
    {"text": "I like to be alone to recharge my energy. / 我喜欢独处来恢复精力。"},
    {"text": "I pay attention to details when making decisions. / 在做决定时，我会关注细节。"},
    {"text": "I always prefer to come up with new and innovative ideas rather than stick to reality. / 我总是更喜欢提出新颖创新的想法，而不是拘泥于现实。"},
    {"text": "I rely on my senses to understand the world around me. / 我依靠感官来理解周围的世界。"},
    {"text": "I often think about various possible and future scenarios. / 我经常思考各种可能的未来场景。"},
    {"text": "When solving problems, I prioritise logical analysis over personal feelings. / 当解决问题时，我优先考虑逻辑分析，而不是个人感受。"},
    {"text": "I make decisions based on the impact of the decision on others. / 我会根据决策对他人的影响来做决定。"},
    {"text": "I value fairness and consistency in judgement. / 我重视判断的公平性和一致性。"},
    {"text": "I consider the impact of my actions on others' feelings. / 我会考虑我的行为对他人感受的影响。"},
    {"text": "I like to plan and organise tasks in advance. / 我喜欢提前规划和组织任务。"},
    {"text": "I prefer to keep some flexible options available for decision-making at any time. / 我更喜欢在任何时候保留一些灵活的选择。"},
    {"text": "I feel more comfortable following a structured daily schedule. / 我更喜欢遵循有结构的日常时间表。"},
    {"text": "I like to adapt to unexpected changes in plans. / 我喜欢适应计划中的意外变化。"},
]

options = [
    ("1 Extremely Disagree / 非常不同意", 1),
    ("2 Disagree / 不同意", 2),
    ("3 Neutral / 中立", 3),
    ("4 Agree / 同意", 4),
    ("5 Extremely Agree / 非常同意", 5),
]

# ───────────── 2. 代理人与品牌映射（Agent and Brand Mapping） ─────────────
agent_map = {
    "ISTJ": {"name":"董明珠 (Dong Mingzhu)", "brand":"Levi’s", "id":"NDZRC3cSilzlQgjmquPB", "link":"https://elevenlabs.io/app/talk-to?agent_id=NDZRC3cSilzlQgjmquPB"},
    "ISFJ": {"name":"马化腾 (Pony Ma Huateng)", "brand":"Uniqlo", "id":"1mwHRUp0SmXKFTwrwcaG", "link":"https://elevenlabs.io/app/talk-to?agent_id=1mwHRUp0SmXKFTwrwcaG"},
    "INFJ": {"name":"许知远 (Xu Zhiyuan)", "brand":"Dries Van Noten", "id":"6GiJcQ6hVB9n49Z22hPf", "link":"https://elevenlabs.io/app/talk-to?agent_id=6GiJcQ6hVB9n49Z22hPf"},
    "INTJ": {"name":"余华 (Yu Hua)", "brand":"Comme des Garçons", "id":"ciRA9NttRulh9DlHHi5F", "link":"https://elevenlabs.io/app/talk-to?agent_id=ciRA9NttRulh9DlHHi5F"},
    "ISTP": {"name":"陈道明 (Chen Daoming)", "brand":"Carhartt", "id":"FlQg64AWr2puSIzWolDN", "link":"https://elevenlabs.io/app/talk-to?agent_id=FlQg64AWr2puSIzWolDN"},
    "ISFP": {"name":"刘诗诗 (Liu Shishi)", "brand":"Madewell", "id":"rT4efTrhn8CZwuc7rWWC", "link":"https://elevenlabs.io/app/talk-to?agent_id=rT4efTrhn8CZwuc7rWWC"},
    "INFP": {"name":"毛不易 (Mao Buyi)", "brand":"Rouje Paris", "id":"ycJJdE9JYFsJt2r9SJP0", "link":"https://elevenlabs.io/app/talk-to?agent_id=ycJJdE9JYFsJt2r9SJP0"},
    "INTP": {"name":"周杰伦 (Jay Chou)", "brand":"Diesel", "id":"fGbHUdbuofvCQyFABJMo", "link":"https://elevenlabs.io/app/talk-to?agent_id=fGbHUdbuofvCQyFABJMo"},
    "ESTP": {"name":"李诞 (Li Dan)", "brand":"Dr Martens", "id":"WHRPBw37ocsQdzFpcm59", "link":"https://elevenlabs.io/app/talk-to?agent_id=WHRPBw37ocsQdzFpcm59"},
    "ESFP": {"name":"刘畊宏 (Will Liu Keng-Hung)", "brand":"Everlane", "id":"8cQHaWAgWPoCwdztKI9i", "link":"https://elevenlabs.io/app/talk-to?agent_id=8cQHaWAgWPoCwdztKI9i"},
    "ENFP": {"name":"王嘉尔 (Jackson Wang)", "brand":"Patagonia", "id":"o4A14q0FgzSdV8xhBPdS", "link":"https://elevenlabs.io/app/talk-to?agent_id=o4A14q0FgzSdV8xhBPdS"},
    "ENTP": {"name":"巩俐 (Gong Li)", "brand":"Ray-Ban", "id":"c4SJDfgatDJoZeVIVQYs", "link":"https://elevenlabs.io/app/talk-to?agent_id=c4SJDfgatDJoZeVIVQYs"},
    "ESTJ": {"name":"白岩松 (Bai Yansong)", "brand":"Mont Blanc", "id":"9tocEyKcvvsIg0TIRuLB", "link":"https://elevenlabs.io/app/talk-to?agent_id=9tocEyKcvvsIg0TIRuLB"},
    "ESFJ": {"name":"李开复 (Kai-Fu Lee)", "brand":"Ralph Lauren", "id":"LO9sHLDwD21x3cDtDKOO", "link":"https://elevenlabs.io/app/talk-to?agent_id=LO9sHLDwD21x3cDtDKOO"},
    "ENFJ": {"name":"马云 (Jack Ma)", "brand":"Moncler Persal", "id":"Nj7I9zWsMaVzNF5VNy4o", "link":"https://elevenlabs.io/app/talk-to?agent_id=Nj7I9zWsMaVzNF5VNy4o"},
    "ENTJ": {"name":"易中天 (Yi Zhongtian)", "brand":"Alexander McQueen", "id":"kHf9AMe6xEPhYuKcNDQ0", "link":"https://elevenlabs.io/app/talk-to?agent_id=kHf9AMe6xEPhYuKcNDQ0"},
}

# ───────────── 3. MBTI计算与分组（Calculate MBTI and Random Group） ─────────────
def calculate_mbti(ans):
    E = ans[0] + ans[2]; I = ans[1] + ans[3]
    S = ans[4] + ans[6]; N = ans[5] + ans[7]
    T = ans[8] + ans[10];F = ans[9] + ans[11]
    J = ans[12]+ ans[14];P = ans[13]+ ans[15]
    mbti = "".join([
        "E" if E>I else "I",
        "S" if S>N else "N",
        "T" if T>F else "F",
        "J" if J>P else "P",
    ])
    group = random.choice(["匹配组 / Match","相反组 / Opposite"])
    agent = agent_map.get(mbti, {"name":"未知","brand":"未知","id":"unknown","link":"#"})
    return mbti, group, agent

# ───────────── 4. Gradio逻辑（Gradio Logic） ─────────────
def start():
    return (
        gr.update(value=None), gr.update(visible=False), gr.update(visible=True),
        f"## 第1题 / Question 1\n\n{questions[0]['text']}",
        1, [None]*len(questions), ""
    )

def next_q(choice, idx, ans):
    ans[idx-1] = dict(options)[choice]
    if idx >= len(questions):
        mbti, group, agent = calculate_mbti(ans)
        link = agent['link']
        html_jump = f"""
            <h3>🎉 测试完成！Quiz Complete!</h3>
            <p>MBTI类型 (Type): <b>{mbti}</b><br>
            分组 (Group): <b>{group}</b><br>
            品牌大使 (Ambassador): <b>{agent['name']}</b><br>
            品牌 (Brand): <b>{agent['brand']}</b></p>
            <p><a href="{link}" target="_blank" style="font-size:20px; color:#007bff; text-decoration:underline;">
            👉 点击此处开始对话 / Click here to start conversation
            </a></p>
            <p>请完成对话后返回此页面继续操作。 / Please return to this page after the conversation.</p>
        """
        return (
            gr.update(visible=False), gr.update(visible=False), gr.update(visible=False),
            gr.update(visible=False), idx, ans, html_jump
        )
    else:
        nxt = idx + 1
        prompt = f"## 第{nxt}题 / Question {nxt}\n\n{questions[nxt-1]['text']}"
        return (
            gr.update(value=None), gr.update(visible=True), gr.update(visible=True),
            prompt, nxt, ans, ""
        )


def prev_q(choice, idx, ans):
    ans[idx-1] = dict(options)[choice]
    if idx <= 1:
        return start()
    prv = idx - 1
    prompt = f"## 第{prv}题 / Question {prv}\n\n{questions[prv-1]['text']}"
    return (
        gr.update(value=None), gr.update(visible=prv>1), gr.update(visible=True),
        prompt, prv, ans, ""
    )

# ───────────── 5. Gradio界面（Gradio Interface） ─────────────
with gr.Blocks(title="MBTI双语测验 / MBTI Bilingual Quiz") as demo:
    gr.Markdown("### 请完成以下16道MBTI测验题 / Please answer the following 16 MBTI questions")

    state_idx = gr.State(1)
    state_ans = gr.State([None]*len(questions))

    question = gr.Markdown()
    choice = gr.Radio([opt[0] for opt in options], label="你的选择 / Your Choice", interactive=True)

    prev_btn = gr.Button("← 上一题 / Previous")
    next_btn = gr.Button("下一题 / Next →")
    result = gr.HTML()

    demo.load(fn=start, outputs=[choice, prev_btn, next_btn, question, state_idx, state_ans, result])

    next_btn.click(fn=next_q, inputs=[choice, state_idx, state_ans],
                   outputs=[choice, prev_btn, next_btn, question, state_idx, state_ans, result])
    prev_btn.click(fn=prev_q, inputs=[choice, state_idx, state_ans],
                   outputs=[choice, prev_btn, next_btn, question, state_idx, state_ans])

demo.launch()